name: sd-grpc-server
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - flit
  - psutil
  - numpy 
  - opencv
  - pip:
    - pystray
    - pygame
    - pyopengl
    - discord
    - aiohttp