name: sd-grpc-server
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - flit
  - psutil
  - numpy 
  - conda-forge::opencv
  - pip:
    - pystray
    - pygame
    - pyopengl
    - discord
    - aiohttp
    - opencv-contrib-python
    - https://github.com/parlance-zz/g-diffuser-aio/releases/download/assets/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl